### ISSUE TITLE
OpenBLAS and LAPACK

### ISSUE THREAD

**Issue by sanerdor** [SethMMorton/cmake_fortran_template#5]
Hi everyone,

I would like to know how to link OpenBLAS and LAPACK libraries to the fortran code.
Could someone give a CMakeLists.txt example of how to link those libraries?

Thank you

**Comment by SethMMorton** [comment]
Can you please explain where your confusion lies? This template *is* an example of how to use those libraries.

**Comment by sanerdor** [comment]
Thank you very much, I made it work.
I seemed to be an issue with the Path of Lapack library
